openapi: 3.0.0
info:
  title: Bar Management API
  version: '0.1'
paths:
  /ingredients:
    get:
      summary: List ingredients
      parameters:
        - in: query
          name: skip
          schema:
            type: integer
        - in: query
          name: limit
          schema:
            type: integer
    post:
      summary: Create ingredient
  /recipes/search:
    get:
      summary: Search recipes from CocktailDB
      parameters:
        - in: query
          name: q
          schema:
            type: string
  /recipes:
    get:
      summary: List recipes
      parameters:
        - in: query
          name: skip
          schema:
            type: integer
        - in: query
          name: limit
          schema:
            type: integer
    post:
      summary: Add recipe from CocktailDB
  /recipes/{recipe_id}:
    get:
      summary: Get recipe
      parameters:
        - in: path
          name: recipe_id
          required: true
          schema:
            type: integer
  /inventory/{id}:
    get:
      summary: Get inventory item
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
    patch:
      summary: Update inventory item
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
